project:
  type: website
  output-dir: docs

website:
#  title: "Daniel Udekwe"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      #- href: blog.qmd
      #  text: Blog
      - href: cv.qmd
        text: Resume
      - href: media.qmd
        text: Media
     

format:
  html:
    #theme:
    #  - cosmo
    #  - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center

editor: visual

